---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: npm install
      - run: ./bin/run.js --version
      - run: ./bin/run.js --help
      - run:
          name: Testing
          command: npm test
  node-22:
    <<: *test
    docker:
      - image: node:22
  node-18:
    <<: *test
    docker:
      - image: node:18
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "package-lock.json"}}
          paths:
            - ~/cli/node_modules
            - ~/.npm
            - /usr/local/lib/node_modules

workflows:
  version: 2
  "sf":
    jobs:
      - node-latest
      - node-22
      - node-18
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
